### ISSUE TITLE
No module named SRC

### ISSUE THREAD

**Issue by Fluxless** [Joyvalley/GWAS_Flow#22]
Hello me again. Thank you again for fixing the docker file for me yesterday and sorry to bother you again so soon.

I have been able to run the sample data successfully, but I am having problems generating Manhattans when I add the flag plot true

``` docker run -v c:/PATH/TO/REPO/GWAS_Flow:/data gwas_flow:latest -x gwas_sample_data/AT_geno.hdf5 -y gwas_sample_data/phenotype.csv -k gwas_sample_data/kinship_ibs_binary_mac5.h5py -o results1.csv --plot True```

It will still produce the results for the GWAS and write them to the repository as a new file, but at the end I get the following error
 
```Traceback (most recent call last):
  File "/home/ubuntu/gwas.py", line 155, in <module>
    import src.plot as plot
ModuleNotFoundError: No module named 'src'```

Is it trying to import and run the plot.py script found in "C:\PATH\TO\REPO\GWAS_Flow\gwas_flow"? 

Thanks

**Comment by iimog** [comment]
This is on me. I forgot to update this import after restructuring the repo. I hope my change fixes it. Unfortunately, I can not check it right now. You'll need to rebuild the docker container after pulling.

**Comment by Fluxless** [comment]
Hi :) - Thank you for the quick response. It is indeed generating a Manhattan plot now perfectly> Looking at your fix now it seems obvious, but I am still quite new to Python in general. 

Just quickly, the sample data only contains the first chromosome I assume? As the GWAS only runs on Chr 1. 

Thanks again, very much looking forwards to running this on my own data.

**Comment by Joyvalley** [comment]
Hi, 
it depends on the dataset the csv data contains 5 chromosomes. I am not 100$ sure about the other datasets anymore to be honest. 
Can you attach the manhattan plot you generated for verification ? 
Kind regards, 
JF

**Comment by Fluxless** [comment]
Hi.
I ran it using the CSV and got 5 chromosomes. The HDF5 geno file only had one. 

HDF5 - 
![image](https://user-images.githubusercontent.com/84780007/131813924-91144564-8c92-4566-8da8-a80ad8a2b1a6.png)

CSV
![image](https://user-images.githubusercontent.com/84780007/131812359-07a2affd-6ce0-42b4-b58c-9a9c726fc9cd.png)

I think it's fine, going to try and run it with my own data today and see how that goes.

**Comment by Joyvalley** [comment]
Hi @Fluxless,
yep that looks alright and the way it is supposed to :-)
Best, 
JJ
