### ISSUE TITLE
tensorflow v2

### ISSUE THREAD

**Issue by arthurkorte** [Joyvalley/GWAS_Flow#8]
Current version of GWAS_FLow is using tensorflow v1, which activates warnings when running on tensorflow v2.
Results are not affected.

**Comment by Joyvalley** [comment]
Hi,
thanks for your Issue.
We are currently working on updating everything to TensorFlow Version 2.0. 
It should be tested and online by Sunday
Best,
Joyvalley

**Comment by iimog** [comment]
duplicate of #5
